version: '3'

volumes:
  bl_trade_aid_local_postgres_data: {}
  bl_trade_aid_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: bl_trade_aid_local_django
    container_name: bl_trade_aid_local_django
      #    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: bl_trade_aid_production_postgres
    container_name: bl_trade_aid_local_postgres
    volumes:
      - bl_trade_aid_local_postgres_data:/var/lib/postgresql/data:Z
      - bl_trade_aid_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: bl_trade_aid_local_docs
    container_name: bl_trade_aid_local_docs
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./bl_trade_aid:/app/bl_trade_aid:z
    ports:
      - "9000:9000"
    command: /start-docs
  networks:
      - bl_network

  networks:
    bl_network:
      driver: bridge
