# Generated by Django 3.2.16 on 2023-02-25 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('secType', models.CharField(help_text='Security type', max_length=12, verbose_name='Security Type')),
                ('conId', models.IntegerField(blank=True, help_text='Not known yet', null=True, verbose_name='Contract ID')),
                ('symbol', models.CharField(help_text='Symbol', max_length=12, verbose_name='Symbol')),
                ('exchange', models.CharField(help_text='Exchange', max_length=12, verbose_name='Exchange')),
                ('currency', models.CharField(help_text='Currency', max_length=12, verbose_name='Currency')),
                ('localSymbol', models.CharField(help_text='LocalSymbol', max_length=12, verbose_name='LocalSymbol')),
                ('tradeClass', models.CharField(help_text='TradeClass', max_length=12, verbose_name='TradeClass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rank', models.IntegerField(blank=True, help_text='Not known yet', null=True, verbose_name='Rank')),
                ('marketName', models.CharField(help_text='MarketName', max_length=12, verbose_name='MarketName')),
                ('minTick', models.DecimalField(decimal_places=2, help_text='Min Tick', max_digits=12, verbose_name='Min Tick')),
                ('orderTypes', models.CharField(help_text='OrderTypes', max_length=100, verbose_name='OrderTypes')),
                ('validExchanges', models.CharField(help_text='ValidExchanges', max_length=100, verbose_name='ValidExchanges')),
                ('priceMagnifier', models.IntegerField(blank=True, help_text='Price Magnifier', null=True, verbose_name='Price Magnifier')),
                ('unerConId', models.IntegerField(blank=True, help_text='', null=True, verbose_name='')),
                ('longName', models.CharField(help_text='Long Name', max_length=100, verbose_name='Long Name')),
                ('contractMonth', models.CharField(help_text='ContractMonth', max_length=100, verbose_name='ContractMonth')),
                ('industry', models.CharField(help_text='industry', max_length=100, verbose_name='industry')),
                ('category', models.CharField(help_text='category', max_length=100, verbose_name='category')),
                ('subcategory', models.CharField(help_text='subcategory', max_length=100, verbose_name='subcategory')),
                ('timeZoneId', models.CharField(help_text='timeZoneId', max_length=100, verbose_name='timeZoneId')),
                ('tradingHours', models.CharField(help_text='timeZoneId', max_length=100, verbose_name='timeZoneId')),
                ('liquidHours', models.CharField(help_text='liquidHours', max_length=100, verbose_name='liquidHours')),
                ('evRule', models.CharField(help_text='evRule', max_length=100, verbose_name='evRule')),
                ('evMultiplier', models.CharField(help_text='evMultiplier', max_length=100, verbose_name='evMultiplier')),
                ('mdSizeMultiplier', models.CharField(help_text='mdSizeevMultiplier', max_length=100, verbose_name='mdSizeevMultiplier')),
                ('aggGroup', models.IntegerField(blank=True, help_text='', null=True, verbose_name='')),
                ('underSymbol', models.CharField(help_text='underSymbol', max_length=100, verbose_name='underSymbol')),
                ('underSecType', models.CharField(help_text='underSecType', max_length=100, verbose_name='underSecType')),
                ('marketRulesId', models.CharField(help_text='marketRulesId', max_length=100, verbose_name='marketRulesId')),
                ('secIdList', models.CharField(help_text='marketRulesId', max_length=100, verbose_name='marketRulesId')),
                ('realExpirationDate', models.CharField(help_text='realExpirationDate', max_length=100, verbose_name='realExpirationDate')),
                ('lastTradeTime', models.CharField(help_text='lastTradeTime', max_length=100, verbose_name='lastTradeTime')),
                ('stockType', models.CharField(help_text='stockType', max_length=100, verbose_name='stockType')),
                ('sizeIncrement', models.DecimalField(decimal_places=2, help_text='sizeIncrement', max_digits=12, verbose_name='sizeIncrement')),
                ('suggestedSizeIncrement', models.DecimalField(decimal_places=2, help_text='suggestedSizeIncrement', max_digits=12, verbose_name='suggestedSizeIncrement')),
                ('cusip', models.CharField(help_text='cusip', max_length=100, verbose_name='cusip')),
                ('ratings', models.CharField(help_text='ratings', max_length=100, verbose_name='ratings')),
                ('descAppend', models.CharField(help_text='descAppend', max_length=100, verbose_name='descAppend')),
                ('bondType', models.CharField(help_text='bondType', max_length=100, verbose_name='bondType')),
                ('cuponType', models.CharField(help_text='cuponType', max_length=100, verbose_name='cuponType')),
                ('callable', models.BooleanField(default=False)),
                ('putable', models.BooleanField(default=False)),
                ('coupon', models.IntegerField(blank=True, help_text='', null=True, verbose_name='')),
                ('convertible', models.BooleanField(default=False)),
                ('maturity', models.CharField(help_text='maturity', max_length=100, verbose_name='maturity')),
                ('issueDate', models.CharField(help_text='issueDate', max_length=100, verbose_name='issueDate')),
                ('nextOptionDate', models.CharField(help_text='nextOptionDate', max_length=100, verbose_name='nextOptionDate')),
                ('nextOptionType', models.CharField(help_text='nextOptionType', max_length=100, verbose_name='nextOptionType')),
                ('nextOptionPartial', models.BooleanField(default=False)),
                ('notes', models.CharField(help_text='notes', max_length=100, verbose_name='notes')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_details', to='patterns.contract', verbose_name='Contract')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the TPO', max_digits=12, verbose_name='Price')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tpo', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_tpo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TPOPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('print', models.CharField(max_length=1, verbose_name='Print')),
                ('tpo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prints', to='patterns.tpo', verbose_name='TPO')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rank', models.IntegerField(blank=True, help_text='Not known yet', null=True, verbose_name='Rank')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the TPO', max_digits=12, verbose_name='Price')),
                ('distance', models.CharField(help_text='distance', max_length=100, verbose_name='distance')),
                ('benchmark', models.CharField(help_text='benchmark', max_length=100, verbose_name='benchmark')),
                ('projection', models.CharField(help_text='projection', max_length=100, verbose_name='projection')),
                ('legsStr', models.CharField(help_text='legsStr', max_length=100, verbose_name='legsStr')),
                ('contractDetails', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scandata', to='patterns.contractdetails', verbose_name='ContractDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the TPO', max_digits=12, verbose_name='Price')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profilechart', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_profilechart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
