# Generated by Django 3.2.16 on 2023-03-30 15:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpoprint',
            name='print',
        ),
        migrations.AddField(
            model_name='profilechart',
            name='batch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='profile_charts', to='patterns.batch', verbose_name='Batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tpo',
            name='profile_chart',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='tpos', to='patterns.profilechart', verbose_name='ProfileChart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tpoprint',
            name='period',
            field=models.CharField(default=0, max_length=1, verbose_name='Period'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('period', models.CharField(max_length=1, verbose_name='Period')),
                ('profile_chart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='patterns.profilechart', verbose_name='ProfileChart')),
                ('tpo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perids', to='patterns.tpo', verbose_name='TPO')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
