# Generated by Django 3.2.16 on 2023-03-07 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdetails',
            name='aggGroup',
            field=models.IntegerField(blank=True, help_text='', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='bondType',
            field=models.CharField(blank=True, help_text='bondType', max_length=100, null=True, verbose_name='bondType'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='category',
            field=models.CharField(blank=True, help_text='category', max_length=100, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_details', to='patterns.contract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='contractMonth',
            field=models.CharField(blank=True, help_text='ContractMonth', max_length=100, null=True, verbose_name='ContractMonth'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='coupon',
            field=models.IntegerField(blank=True, help_text='', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='cuponType',
            field=models.CharField(blank=True, help_text='cuponType', max_length=100, null=True, verbose_name='cuponType'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='cusip',
            field=models.CharField(blank=True, help_text='cusip', max_length=100, null=True, verbose_name='cusip'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='descAppend',
            field=models.CharField(blank=True, help_text='descAppend', max_length=100, null=True, verbose_name='descAppend'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='evMultiplier',
            field=models.CharField(blank=True, help_text='evMultiplier', max_length=100, null=True, verbose_name='evMultiplier'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='evRule',
            field=models.CharField(blank=True, help_text='evRule', max_length=100, null=True, verbose_name='evRule'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='industry',
            field=models.CharField(blank=True, help_text='industry', max_length=100, null=True, verbose_name='industry'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='issueDate',
            field=models.CharField(blank=True, help_text='issueDate', max_length=100, null=True, verbose_name='issueDate'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='lastTradeTime',
            field=models.CharField(blank=True, help_text='lastTradeTime', max_length=100, null=True, verbose_name='lastTradeTime'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='liquidHours',
            field=models.CharField(blank=True, help_text='liquidHours', max_length=100, null=True, verbose_name='liquidHours'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='longName',
            field=models.CharField(blank=True, help_text='Long Name', max_length=100, null=True, verbose_name='Long Name'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='marketName',
            field=models.CharField(blank=True, help_text='MarketName', max_length=12, null=True, verbose_name='MarketName'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='marketRulesId',
            field=models.CharField(blank=True, help_text='marketRulesId', max_length=100, null=True, verbose_name='marketRulesId'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='maturity',
            field=models.CharField(blank=True, help_text='maturity', max_length=100, null=True, verbose_name='maturity'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='mdSizeMultiplier',
            field=models.CharField(blank=True, help_text='mdSizeevMultiplier', max_length=100, null=True, verbose_name='mdSizeevMultiplier'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='minTick',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Min Tick', max_digits=12, null=True, verbose_name='Min Tick'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='nextOptionDate',
            field=models.CharField(blank=True, help_text='nextOptionDate', max_length=100, null=True, verbose_name='nextOptionDate'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='nextOptionType',
            field=models.CharField(blank=True, help_text='nextOptionType', max_length=100, null=True, verbose_name='nextOptionType'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='notes',
            field=models.CharField(blank=True, help_text='notes', max_length=100, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='orderTypes',
            field=models.CharField(blank=True, help_text='OrderTypes', max_length=100, null=True, verbose_name='OrderTypes'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='ratings',
            field=models.CharField(blank=True, help_text='ratings', max_length=100, null=True, verbose_name='ratings'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='realExpirationDate',
            field=models.CharField(blank=True, help_text='realExpirationDate', max_length=100, null=True, verbose_name='realExpirationDate'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='secIdList',
            field=models.CharField(blank=True, help_text='marketRulesId', max_length=100, null=True, verbose_name='marketRulesId'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='stockType',
            field=models.CharField(blank=True, help_text='stockType', max_length=100, null=True, verbose_name='stockType'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='subcategory',
            field=models.CharField(blank=True, help_text='subcategory', max_length=100, null=True, verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='timeZoneId',
            field=models.CharField(blank=True, help_text='timeZoneId', max_length=100, null=True, verbose_name='timeZoneId'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='tradingHours',
            field=models.CharField(blank=True, help_text='timeZoneId', max_length=100, null=True, verbose_name='timeZoneId'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='underSecType',
            field=models.CharField(blank=True, help_text='underSecType', max_length=100, null=True, verbose_name='underSecType'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='underSymbol',
            field=models.CharField(blank=True, help_text='underSymbol', max_length=100, null=True, verbose_name='underSymbol'),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='unerConId',
            field=models.IntegerField(blank=True, help_text='', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='validExchanges',
            field=models.CharField(blank=True, help_text='ValidExchanges', max_length=100, null=True, verbose_name='ValidExchanges'),
        ),
        migrations.AlterField(
            model_name='scandata',
            name='benchmark',
            field=models.CharField(blank=True, help_text='benchmark', max_length=100, null=True, verbose_name='benchmark'),
        ),
        migrations.AlterField(
            model_name='scandata',
            name='distance',
            field=models.CharField(blank=True, help_text='distance', max_length=100, null=True, verbose_name='distance'),
        ),
        migrations.AlterField(
            model_name='scandata',
            name='legsStr',
            field=models.CharField(blank=True, help_text='legsStr', max_length=100, null=True, verbose_name='legsStr'),
        ),
        migrations.AlterField(
            model_name='scandata',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of the TPO', max_digits=12, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='scandata',
            name='projection',
            field=models.CharField(blank=True, help_text='projection', max_length=100, null=True, verbose_name='projection'),
        ),
    ]
