# Generated by Django 3.2.16 on 2023-03-15 14:49

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_auto_20230307_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='date')),
                ('open', models.DecimalField(decimal_places=2, help_text='open', max_digits=12, verbose_name='open')),
                ('high', models.DecimalField(decimal_places=2, help_text='high', max_digits=12, verbose_name='high')),
                ('low', models.DecimalField(decimal_places=2, help_text='low', max_digits=12, verbose_name='low')),
                ('close', models.DecimalField(decimal_places=2, help_text='close', max_digits=12, verbose_name='close')),
                ('volume', models.DecimalField(decimal_places=2, help_text='volume', max_digits=12, verbose_name='volume')),
                ('average', models.DecimalField(decimal_places=2, help_text='average', max_digits=12, verbose_name='average')),
                ('barCount', models.IntegerField(help_text='barCount', verbose_name='barCount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='aggGroup',
            field=models.IntegerField(blank=True, help_text='', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='coupon',
            field=models.IntegerField(blank=True, help_text='', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='unerConId',
            field=models.IntegerField(blank=True, help_text='', null=True, verbose_name=''),
        ),
    ]
