# Generated by Django 3.2.16 on 2023-04-13 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_auto_20230330_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='bardata',
            name='batch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='bar_data', to='patterns.batch', verbose_name='Batch'),
            preserve_default=False,
        ),
    ]
