# Generated by Django 3.2.16 on 2023-08-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0003_bardata_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilechart',
            name='price',
        ),
        migrations.AddField(
            model_name='profilechart',
            name='chart_file',
            field=models.FileField(blank=True, null=True, upload_to='charts/'),
        ),
        migrations.AddField(
            model_name='profilechart',
            name='symbol',
            field=models.CharField(default='NOSYMBOL', max_length=10, verbose_name='Symbol'),
            preserve_default=False,
        ),
    ]
