# Generated by Django 3.2.16 on 2023-10-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0004_auto_20230816_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='bardata',
            name='symbol',
            field=models.CharField(default='PANCHO', max_length=10, verbose_name='Symbol'),
            preserve_default=False,
        ),
    ]
