# Generated by Django 3.2.16 on 2023-11-09 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0007_auto_20231109_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, help_text='Name of the rule', max_length=100, null=True, verbose_name='Name')),
                ('control_point_band_ticks', models.IntegerField(blank=True, help_text='Ticks allowed for the band', null=True, verbose_name='Control Point Band Ticks')),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='patterns.experiment', verbose_name='Experiment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
