# Generated by Django 3.2.16 on 2023-11-10 11:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0008_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('symbol', models.CharField(help_text='Symbol', max_length=12, verbose_name='Symbol')),
                ('positive_outcome', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positive_outcomes', to='patterns.batch', verbose_name='Batch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PositiveOutcome',
        ),
    ]
