# Generated by Django 3.2.16 on 2023-11-10 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0009_auto_20231110_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedcontract',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_contracts', to='patterns.batch', verbose_name='Batch'),
        ),
    ]
