# Generated by Django 3.2.16 on 2023-11-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0011_excludedcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='days_offset',
            field=models.IntegerField(blank=True, help_text='Day(s) that will be compared with the rest', null=True, verbose_name='DayOffset'),
        ),
    ]
