# Generated by Django 3.2.16 on 2023-11-24 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0012_rule_days_offset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('shadow_mode', models.BooleanField(default=False)),
                ('open_price', models.DecimalField(decimal_places=2, help_text='open position price', max_digits=12, verbose_name='open_price')),
                ('close_price', models.DecimalField(decimal_places=2, help_text='close position price', max_digits=12, verbose_name='close_price')),
                ('direction', models.CharField(choices=[('L', 'Long'), ('S', 'Short')], default='L', help_text='Direction of the position', max_length=1, verbose_name='Direction')),
                ('processed_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='patterns.processedcontract', verbose_name='ProcessedContract')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
