# Generated by Django 3.2.16 on 2023-11-25 10:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0014_auto_20231124_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('alert_price', models.DecimalField(decimal_places=4, max_digits=6)),
                ('operator', models.CharField(choices=[('GT', 'Greater Than'), ('LT', 'Less Than')], max_length=2)),
                ('processed_contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='patterns.processedcontract', verbose_name='ProcessedContract')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
