# Generated by Django 3.2.16 on 2023-11-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0017_rename_alert_alert_alert_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='ticks_offset',
            field=models.IntegerField(blank=True, help_text='Ticks that will be the offset of the last(s) days from the rest of the pack', null=True, verbose_name='Ticks'),
        ),
    ]
