# Generated by Django 3.2.16 on 2023-12-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0019_position_positive_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='days_returned',
            field=models.IntegerField(blank=True, help_text='How many days should be returned for each symbols used to fetch and validate', null=True, verbose_name='DaysReturned'),
        ),
    ]
