# Generated by Django 3.2.16 on 2023-12-05 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0020_rule_days_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='instrument',
            field=models.CharField(blank=True, help_text='Instrument', max_length=100, null=True, verbose_name='Instrument'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='location_code',
            field=models.CharField(blank=True, help_text='Location of the instrument', max_length=100, null=True, verbose_name='Location_Code'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='scan_code',
            field=models.CharField(blank=True, help_text='Special code for scanning', max_length=100, null=True, verbose_name='Scan_Code'),
        ),
        migrations.CreateModel(
            name='QueryParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('parameter_name', models.CharField(blank=True, help_text='Name of the parameter', max_length=100, null=True, verbose_name='Name')),
                ('parameter_value', models.CharField(blank=True, help_text='Value of the parameter', max_length=100, null=True, verbose_name='Value')),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='query_parameters', to='patterns.experiment', verbose_name='Experiment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
