# Generated by Django 3.2.16 on 2023-12-06 10:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0021_auto_20231205_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='experiment',
        ),
        migrations.CreateModel(
            name='RuleExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='patterns.experiment', verbose_name='Experiment')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='patterns.rule', verbose_name='Rule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='experiment',
            field=models.ManyToManyField(blank=True, null=True, through='patterns.RuleExperiment', to='patterns.Experiment', verbose_name='Experiment'),
        ),
    ]
