# Generated by Django 3.2.16 on 2023-12-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0022_auto_20231206_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleexperiment',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_rules', to='patterns.experiment', verbose_name='Experiment'),
        ),
        migrations.AlterField(
            model_name='ruleexperiment',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_experiments', to='patterns.rule', verbose_name='Rule'),
        ),
    ]
