# Generated by Django 3.2.16 on 2023-12-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0025_experiment_difference_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='difference_direction',
        ),
        migrations.AddField(
            model_name='rule',
            name='difference_direction',
            field=models.CharField(choices=[('DOWN', 'Down'), ('UP', 'Up')], default=None, help_text='Direction of the position', max_length=4, verbose_name='Direction'),
        ),
    ]
