# Generated by Django 3.2.16 on 2023-12-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0026_auto_20231212_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='difference_direction',
            field=models.CharField(blank=True, choices=[('DOWN', 'Down'), ('UP', 'Up')], default=None, help_text='Direction of the position', max_length=4, null=True, verbose_name='Direction'),
        ),
    ]
