# Generated by Django 3.2.16 on 2023-12-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0028_alter_rule_experiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='above_price',
            field=models.CharField(blank=True, help_text='Above Pride', max_length=100, null=True, verbose_name='Above_Price'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='above_volume',
            field=models.CharField(blank=True, help_text='Above Volume', max_length=100, null=True, verbose_name='Above_Volume'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='below_price',
            field=models.CharField(blank=True, help_text='Below Price', max_length=100, null=True, verbose_name='Below_Price'),
        ),
    ]
