# Generated by Django 3.2.16 on 2023-12-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0029_auto_20231214_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='market_cap_above',
            field=models.CharField(blank=True, help_text='Market_Cap_Above', max_length=100, null=True, verbose_name='Market_Cap_Above'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='market_cap_below',
            field=models.CharField(blank=True, help_text='Market_Cap_Below', max_length=100, null=True, verbose_name='Market_Cap_Below'),
        ),
    ]
