# Generated by Django 3.2.16 on 2024-01-04 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0030_auto_20231214_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, help_text='Name of the rule set', max_length=100, null=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='average_option_volume_above',
            field=models.IntegerField(blank=True, help_text='AverageOptionVolumeAbove', max_length=100, null=True, verbose_name='AverageOptionVolumeAbove'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='coupon_rate_above',
            field=models.IntegerField(blank=True, help_text='Coupon_Rate_Above', null=True, verbose_name='Coupon_Rate_Above'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='coupon_rate_below',
            field=models.IntegerField(blank=True, help_text='Coupon_Rate_Below', null=True, verbose_name='Coupon_Rate_Below'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='days_returned',
            field=models.IntegerField(blank=True, help_text='How many days should be returned for each symbolsused to fetch and validate', null=True, verbose_name='DaysReturned'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='exclude_convertible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='stock_type_filter',
            field=models.CharField(blank=True, default='', help_text='stockTypeFilter', max_length=100, null=True, verbose_name='stockTypeFilter'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='above_price',
            field=models.CharField(blank=True, default='', help_text='Above Price', max_length=100, null=True, verbose_name='Above_Price'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='above_volume',
            field=models.CharField(blank=True, default='', help_text='Above Volume', max_length=100, null=True, verbose_name='Above_Volume'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='below_price',
            field=models.CharField(blank=True, default='', help_text='Below Price', max_length=100, null=True, verbose_name='Below_Price'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='market_cap_above',
            field=models.CharField(blank=True, default='', help_text='Market_Cap_Above', max_length=100, null=True, verbose_name='Market_Cap_Above'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='market_cap_below',
            field=models.CharField(blank=True, default='', help_text='Market_Cap_Below', max_length=100, null=True, verbose_name='Market_Cap_Below'),
        ),
        migrations.CreateModel(
            name='RuleSetExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_sets', to='patterns.experiment', verbose_name='Experiment')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_set_experiments', to='patterns.ruleset', verbose_name='RuleSet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ruleset',
            name='experiment',
            field=models.ManyToManyField(through='patterns.RuleSetExperiment', to='patterns.Experiment', verbose_name='Experiment'),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='rules',
            field=models.ManyToManyField(to='patterns.Rule', verbose_name='Rules'),
        ),
    ]
