# Generated by Django 3.2.16 on 2024-01-05 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0031_auto_20240104_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedcontract',
            name='applied_rule_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_contracts', to='patterns.ruleset', verbose_name='Batch'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='average_option_volume_above',
            field=models.IntegerField(blank=True, help_text='AverageOptionVolumeAbove', null=True, verbose_name='AverageOptionVolumeAbove'),
        ),
    ]
