# Generated by Django 3.2.16 on 2024-01-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0032_auto_20240105_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulesetexperiment',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='rulesetexperiment',
            name='rule_set',
        ),
        migrations.RemoveField(
            model_name='processedcontract',
            name='applied_rule_set',
        ),
        migrations.DeleteModel(
            name='RuleSet',
        ),
        migrations.DeleteModel(
            name='RuleSetExperiment',
        ),
    ]
