# Generated by Django 3.2.16 on 2024-01-19 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0033_auto_20240118_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedcontract',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procesec_contracts', to='patterns.rule', verbose_name='Rule'),
        ),
    ]
