# Generated by Django 3.2.16 on 2024-01-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0035_alter_rule_difference_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='days_offset',
            field=models.IntegerField(default=1, help_text='Day(s) that will be compared with the rest', verbose_name='DayOffset'),
        ),
    ]
