# Generated by Django 3.2.16 on 2024-02-02 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0038_alter_experiment_days_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedcontract',
            name='profile_chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_contracts', to='patterns.profilechart', verbose_name='ProfileChart'),
        ),
    ]
